spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springBootMongoDB

custom:
  data:
    mongodb:
      user: 
      dbAuth: 
      password: 

logging:
  level:
    root: INFO