spring:
  data:
    mongodb:
      host: 10.0.202.78
      port: 27017
      database: springBootMongoDB

custom:
  data:
    mongodb:
      user: admin
      dbAuth: admin
      password: secret

logging:
  level:
    root: INFO
